import 'package:flutter/material.dart';

import '../../core/constants/app_colors.dart';
import 'demo_catalog_support.dart';
import 'demo_models.dart';

const String _topicProgrammingLanguages = 'programming_languages';
const String _topicDataAnalytics = 'data_analytics';
const String _topicAi = 'ai';
const String _topicSqlDatabases = 'sql_databases';
const String _topicSoftSkills = 'soft_skills';

List<CommunityCourse> buildDiscoveryCourses() {
  final authors = <String, CommunityCourseAuthor>{
    'aruzhan_bek': const CommunityCourseAuthor(
      id: 'aruzhan_bek',
      name: 'Aruzhan Bek',
      role: 'Product Engineer',
      accentLabel: 'Demo design',
      followersCount: 18200,
      courseCount: 6,
      topicKeys: <String>[_topicSoftSkills, _topicProgrammingLanguages],
    ),
    'maksat_y': const CommunityCourseAuthor(
      id: 'maksat_y',
      name: 'Maksat Y.',
      role: 'Analytics Lead',
      accentLabel: 'SQL coaching',
      followersCount: 14600,
      courseCount: 7,
      topicKeys: <String>[_topicDataAnalytics, _topicSqlDatabases],
    ),
    'dana_s': const CommunityCourseAuthor(
      id: 'dana_s',
      name: 'Dana S.',
      role: 'ML Engineer',
      accentLabel: 'Research to product',
      followersCount: 17300,
      courseCount: 6,
      topicKeys: <String>[_topicAi, _topicDataAnalytics],
    ),
    'rustem_k': const CommunityCourseAuthor(
      id: 'rustem_k',
      name: 'Rustem K.',
      role: 'Staff Backend Engineer',
      accentLabel: 'Security review',
      followersCount: 11400,
      courseCount: 5,
      topicKeys: <String>[_topicSqlDatabases, _topicProgrammingLanguages],
    ),
    'aigerim_n': const CommunityCourseAuthor(
      id: 'aigerim_n',
      name: 'Aigerim N.',
      role: 'Design Systems Lead',
      accentLabel: 'UI systems',
      followersCount: 9300,
      courseCount: 4,
      topicKeys: <String>[_topicSoftSkills, _topicProgrammingLanguages],
    ),
    'tomiris_a': const CommunityCourseAuthor(
      id: 'tomiris_a',
      name: 'Tomiris A.',
      role: 'Learning Architect',
      accentLabel: 'Skill maps',
      followersCount: 12500,
      courseCount: 5,
      topicKeys: <String>[_topicSoftSkills, _topicProgrammingLanguages],
    ),
    'ilia_v': const CommunityCourseAuthor(
      id: 'ilia_v',
      name: 'Ilia V.',
      role: 'DevOps Mentor',
      accentLabel: 'Linux workflows',
      followersCount: 8900,
      courseCount: 4,
      topicKeys: <String>[_topicProgrammingLanguages, _topicSoftSkills],
    ),
    'saule_m': const CommunityCourseAuthor(
      id: 'saule_m',
      name: 'Saule M.',
      role: 'Data Analyst',
      accentLabel: 'Metrics stories',
      followersCount: 10200,
      courseCount: 6,
      topicKeys: <String>[_topicDataAnalytics, _topicSqlDatabases],
    ),
    'nurislam_g': const CommunityCourseAuthor(
      id: 'nurislam_g',
      name: 'Nurislam G.',
      role: 'AI Product Lead',
      accentLabel: 'Prompt systems',
      followersCount: 13700,
      courseCount: 6,
      topicKeys: <String>[_topicAi, _topicSoftSkills],
    ),
    'alina_p': const CommunityCourseAuthor(
      id: 'alina_p',
      name: 'Alina P.',
      role: 'Database Engineer',
      accentLabel: 'Query tuning',
      followersCount: 9800,
      courseCount: 5,
      topicKeys: <String>[_topicSqlDatabases, _topicDataAnalytics],
    ),
  };

  const seeds = <_DiscoveryCourseSeed>[
    _DiscoveryCourseSeed(
      id: 'course_portfolio_engineering',
      title: 'Portfolio Engineering for Students',
      subtitle: 'Turn side projects into convincing product stories',
      description: 'Structure projects, demos, and README narratives for internships and showcases.',
      level: 'Beginner',
      rating: 4.8,
      enrollmentCount: 1240,
      estimatedHours: 5,
      color: AppColors.primary,
      authorId: 'aruzhan_bek',
      categoryKey: _topicSoftSkills,
      topicKeys: <String>[_topicSoftSkills, _topicProgrammingLanguages],
      searchKeywords: <String>['portfolio', 'career', 'storytelling'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['portfolio', 'career', 'frontend'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_sql_for_analysts',
      title: 'SQL for Product Analysts',
      subtitle: 'Queries, cohorts, funnels, and experiment reads',
      description: 'Use practical SQL patterns for product questions, funnels, and metric reviews.',
      level: 'Intermediate',
      rating: 4.7,
      enrollmentCount: 980,
      estimatedHours: 7,
      color: Color(0xFFFFD166),
      authorId: 'maksat_y',
      categoryKey: _topicSqlDatabases,
      topicKeys: <String>[_topicSqlDatabases, _topicDataAnalytics],
      searchKeywords: <String>['sql', 'analytics', 'funnels'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['sql', 'analytics', 'experiments'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_ml_journal_club',
      title: 'ML Journal Club Lite',
      subtitle: 'Read one paper idea and map it into product language',
      description: 'Connect research ideas to product intuition without dense notation or dead ends.',
      level: 'Intermediate',
      rating: 4.9,
      enrollmentCount: 560,
      estimatedHours: 4,
      color: Color(0xFFA78BFA),
      authorId: 'dana_s',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi, _topicDataAnalytics],
      searchKeywords: <String>['ml', 'research', 'papers'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['ml', 'research', 'reading'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_secure_api_clinic',
      title: 'Secure API Clinic',
      subtitle: 'A guided walkthrough of auth, validation, and incident hints',
      description: 'A backend-minded course focused on defensive API design and practical review habits.',
      level: 'Advanced',
      rating: 4.6,
      enrollmentCount: 430,
      estimatedHours: 6,
      color: AppColors.danger,
      authorId: 'rustem_k',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages, _topicSoftSkills],
      searchKeywords: <String>['api', 'security', 'backend'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['security', 'backend', 'api'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_design_systems_from_scratch',
      title: 'Design Systems from Scratch',
      subtitle: 'Tokens, hierarchy, reusable components, and product coherence',
      description: 'Frame design systems as a language for teams instead of a loose bag of components.',
      level: 'Intermediate',
      rating: 4.8,
      enrollmentCount: 760,
      estimatedHours: 5,
      color: Color(0xFFFF9F68),
      authorId: 'aigerim_n',
      categoryKey: _topicSoftSkills,
      topicKeys: <String>[_topicSoftSkills, _topicProgrammingLanguages],
      searchKeywords: <String>['design systems', 'ui', 'components'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['design-system', 'frontend', 'mobile'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_dart_first_widget',
      title: 'Dart from First Widget',
      subtitle: 'Variables, widgets, and confident app-building habits',
      description: 'Use Dart basics to build clean UI intuition and calmer coding habits.',
      level: 'Beginner',
      rating: 4.7,
      enrollmentCount: 1520,
      estimatedHours: 6,
      color: Color(0xFF56CCF2),
      authorId: 'tomiris_a',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages],
      searchKeywords: <String>['dart', 'flutter', 'widgets'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['dart', 'flutter', 'language'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_python_automation',
      title: 'Python for Automation',
      subtitle: 'Scripts, data cleanup, and repeatable workflows',
      description: 'Use Python to automate routine work, cleanup data, and ship quick tools.',
      level: 'Beginner',
      rating: 4.8,
      enrollmentCount: 1880,
      estimatedHours: 8,
      color: Color(0xFF74B9FF),
      authorId: 'ilia_v',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages, _topicDataAnalytics, _topicAi],
      searchKeywords: <String>['python', 'automation', 'scripts'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['python', 'automation', 'scripts'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_javascript_patterns',
      title: 'JavaScript Patterns Sprint',
      subtitle: 'Functions, arrays, and practical browser-side habits',
      description: 'A quick pass through reusable JavaScript patterns for product teams.',
      level: 'Beginner',
      rating: 4.6,
      enrollmentCount: 1320,
      estimatedHours: 5,
      color: Color(0xFFFFC857),
      authorId: 'aigerim_n',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages],
      searchKeywords: <String>['javascript', 'js', 'frontend'],
      isPopular: true,
      isRecommended: false,
      tags: <String>['javascript', 'patterns', 'frontend'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_typescript_interfaces',
      title: 'TypeScript for Product Interfaces',
      subtitle: 'Types, safety, and maintainable UI contracts',
      description: 'Learn how TypeScript makes interface work calmer and more predictable.',
      level: 'Intermediate',
      rating: 4.7,
      enrollmentCount: 1160,
      estimatedHours: 6,
      color: Color(0xFF4E89FF),
      authorId: 'aigerim_n',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages],
      searchKeywords: <String>['typescript', 'types', 'frontend'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['typescript', 'types', 'interfaces'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_go_services',
      title: 'Go Services Bootcamp',
      subtitle: 'Structured backend services, logs, and concurrency basics',
      description: 'A backend-flavored Go course focused on clean service design.',
      level: 'Intermediate',
      rating: 4.6,
      enrollmentCount: 840,
      estimatedHours: 7,
      color: Color(0xFF00B8D9),
      authorId: 'rustem_k',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages, _topicSqlDatabases],
      searchKeywords: <String>['go', 'golang', 'services'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['go', 'backend', 'services'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_kotlin_android',
      title: 'Kotlin Android Essentials',
      subtitle: 'Native Android thinking through a modern language lens',
      description: 'Understand Kotlin syntax and mobile-focused coding habits through small examples.',
      level: 'Intermediate',
      rating: 4.5,
      enrollmentCount: 790,
      estimatedHours: 7,
      color: Color(0xFF7C4DFF),
      authorId: 'tomiris_a',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages],
      searchKeywords: <String>['kotlin', 'android', 'mobile'],
      isPopular: false,
      isRecommended: false,
      tags: <String>['kotlin', 'android', 'mobile'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_swiftui_basics',
      title: 'SwiftUI Basics for Builders',
      subtitle: 'State, screens, and layout on Apple platforms',
      description: 'Understand SwiftUI primitives without getting lost in boilerplate.',
      level: 'Intermediate',
      rating: 4.6,
      enrollmentCount: 720,
      estimatedHours: 6,
      color: Color(0xFF90CAF9),
      authorId: 'tomiris_a',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages],
      searchKeywords: <String>['swift', 'swiftui', 'ios'],
      isPopular: false,
      isRecommended: false,
      tags: <String>['swift', 'ios', 'mobile'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_rust_systems',
      title: 'Rust Systems Track',
      subtitle: 'Ownership, safety, and modern systems intuition',
      description: 'A beginner-friendly route into Rust for developers who enjoy systems thinking.',
      level: 'Advanced',
      rating: 4.8,
      enrollmentCount: 650,
      estimatedHours: 8,
      color: Color(0xFFFFA726),
      authorId: 'ilia_v',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages],
      searchKeywords: <String>['rust', 'systems', 'ownership'],
      isPopular: false,
      isRecommended: false,
      tags: <String>['rust', 'systems', 'performance'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_linux_terminal',
      title: 'Linux Terminal for Engineers',
      subtitle: 'Commands, pipes, and practical daily workflows',
      description: 'A daily-driver course for learning Linux fluency through useful routines.',
      level: 'Beginner',
      rating: 4.8,
      enrollmentCount: 1650,
      estimatedHours: 5,
      color: Color(0xFF66BB6A),
      authorId: 'ilia_v',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages, _topicSoftSkills],
      searchKeywords: <String>['linux', 'bash', 'terminal'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['linux', 'terminal', 'bash'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_data_storytelling',
      title: 'Data Storytelling Studio',
      subtitle: 'Turn dashboards into decisions and narratives',
      description: 'Learn how to frame metrics, charts, and recommendations for product teams.',
      level: 'Beginner',
      rating: 4.7,
      enrollmentCount: 1120,
      estimatedHours: 5,
      color: Color(0xFFF48FB1),
      authorId: 'saule_m',
      categoryKey: _topicDataAnalytics,
      topicKeys: <String>[_topicDataAnalytics, _topicSoftSkills],
      searchKeywords: <String>['analytics', 'storytelling', 'dashboards'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['analytics', 'storytelling', 'presentation'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_statistics_metrics',
      title: 'Statistics for Product Metrics',
      subtitle: 'Variance, confidence, signal, and decision quality',
      description: 'Use practical statistics intuition to interpret metric movement more responsibly.',
      level: 'Intermediate',
      rating: 4.8,
      enrollmentCount: 970,
      estimatedHours: 7,
      color: Color(0xFFAB47BC),
      authorId: 'maksat_y',
      categoryKey: _topicDataAnalytics,
      topicKeys: <String>[_topicDataAnalytics],
      searchKeywords: <String>['statistics', 'metrics', 'confidence'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['statistics', 'metrics', 'experiments'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_experiment_sql',
      title: 'Experiment Readouts with SQL',
      subtitle: 'Build A/B test reads with cleaner query flows',
      description: 'Combine SQL and experiment thinking to produce review-ready readouts.',
      level: 'Intermediate',
      rating: 4.6,
      enrollmentCount: 690,
      estimatedHours: 6,
      color: Color(0xFFFFD54F),
      authorId: 'maksat_y',
      categoryKey: _topicDataAnalytics,
      topicKeys: <String>[_topicDataAnalytics, _topicSqlDatabases],
      searchKeywords: <String>['ab test', 'sql', 'experiments'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['sql', 'experiments', 'analysis'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_postgresql_performance',
      title: 'PostgreSQL Performance First',
      subtitle: 'Indexes, plans, and healthy query habits',
      description: 'Make PostgreSQL feel less mysterious by learning the few levers that matter most.',
      level: 'Advanced',
      rating: 4.7,
      enrollmentCount: 740,
      estimatedHours: 7,
      color: Color(0xFF42A5F5),
      authorId: 'alina_p',
      categoryKey: _topicSqlDatabases,
      topicKeys: <String>[_topicSqlDatabases],
      searchKeywords: <String>['postgresql', 'indexes', 'query plan'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['postgresql', 'performance', 'database'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_data_modeling_workshop',
      title: 'Data Modeling Workshop',
      subtitle: 'Design tables and entities that age well',
      description: 'Learn schema design tradeoffs through product-flavored examples and refactors.',
      level: 'Intermediate',
      rating: 4.7,
      enrollmentCount: 860,
      estimatedHours: 6,
      color: Color(0xFF26C6DA),
      authorId: 'alina_p',
      categoryKey: _topicSqlDatabases,
      topicKeys: <String>[_topicSqlDatabases, _topicDataAnalytics],
      searchKeywords: <String>['schema', 'database design', 'entities'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['database', 'schema', 'sql'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_prompt_design_builders',
      title: 'Prompt Design for Builders',
      subtitle: 'Design prompts that fit product tasks and review loops',
      description: 'A practical introduction to prompt structure, evaluation, and safer iteration.',
      level: 'Beginner',
      rating: 4.8,
      enrollmentCount: 1590,
      estimatedHours: 4,
      color: Color(0xFFCE93D8),
      authorId: 'nurislam_g',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi, _topicSoftSkills],
      searchKeywords: <String>['prompting', 'llm', 'ai'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['ai', 'prompting', 'llm'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_llm_evaluation',
      title: 'LLM Evaluation Patterns',
      subtitle: 'Rubrics, failure modes, and small reliable test sets',
      description: 'Learn how to evaluate AI features with deterministic checks and realistic examples.',
      level: 'Advanced',
      rating: 4.7,
      enrollmentCount: 620,
      estimatedHours: 6,
      color: Color(0xFFB39DDB),
      authorId: 'dana_s',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi, _topicDataAnalytics],
      searchKeywords: <String>['llm eval', 'ai quality', 'rubric'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['llm', 'evaluation', 'ai'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_feature_lab',
      title: 'Feature Engineering Lab',
      subtitle: 'From raw columns to useful model signals',
      description: 'Map business understanding into structured features with lighter-weight math.',
      level: 'Intermediate',
      rating: 4.6,
      enrollmentCount: 540,
      estimatedHours: 7,
      color: Color(0xFF8E24AA),
      authorId: 'dana_s',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi, _topicDataAnalytics],
      searchKeywords: <String>['feature engineering', 'ml', 'analytics'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['ml', 'features', 'analytics'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_computer_vision',
      title: 'Computer Vision Starter',
      subtitle: 'Images, embeddings, and practical product examples',
      description: 'Build intuition for vision workflows without turning the course into a math wall.',
      level: 'Intermediate',
      rating: 4.5,
      enrollmentCount: 480,
      estimatedHours: 6,
      color: Color(0xFF9575CD),
      authorId: 'dana_s',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi],
      searchKeywords: <String>['computer vision', 'images', 'cnn'],
      isPopular: false,
      isRecommended: false,
      tags: <String>['vision', 'ml', 'images'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_recommender_systems',
      title: 'Recommender Systems Primer',
      subtitle: 'Rank, retrieve, and evaluate recommendations',
      description: 'A product-minded map of recommenders, from candidate generation to evaluation.',
      level: 'Advanced',
      rating: 4.7,
      enrollmentCount: 510,
      estimatedHours: 8,
      color: Color(0xFF7E57C2),
      authorId: 'nurislam_g',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi, _topicDataAnalytics],
      searchKeywords: <String>['recommender', 'ranking', 'retrieval'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['recommender', 'ranking', 'ml'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_feedback_communication',
      title: 'Feedback That Helps Teams Ship',
      subtitle: 'Write, receive, and act on feedback without friction',
      description: 'Use structured communication to keep review loops honest, kind, and useful.',
      level: 'Beginner',
      rating: 4.8,
      enrollmentCount: 930,
      estimatedHours: 3,
      color: Color(0xFFF06292),
      authorId: 'aruzhan_bek',
      categoryKey: _topicSoftSkills,
      topicKeys: <String>[_topicSoftSkills],
      searchKeywords: <String>['feedback', 'communication', 'teamwork'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['soft-skills', 'feedback', 'communication'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_interview_storytelling',
      title: 'Interview Storytelling for Engineers',
      subtitle: 'Turn experience into clear and credible answers',
      description: 'Practice concise stories for interviews, demos, and mentor conversations.',
      level: 'Beginner',
      rating: 4.7,
      enrollmentCount: 1180,
      estimatedHours: 4,
      color: Color(0xFFFF8A80),
      authorId: 'aruzhan_bek',
      categoryKey: _topicSoftSkills,
      topicKeys: <String>[_topicSoftSkills],
      searchKeywords: <String>['interview', 'storytelling', 'career'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['career', 'interview', 'storytelling'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_leadership_juniors',
      title: 'Leadership for Junior Engineers',
      subtitle: 'Ownership, alignment, and helpful initiative',
      description: 'Learn leadership signals that make you reliable before you have formal authority.',
      level: 'Intermediate',
      rating: 4.6,
      enrollmentCount: 670,
      estimatedHours: 4,
      color: Color(0xFFF48FB1),
      authorId: 'tomiris_a',
      categoryKey: _topicSoftSkills,
      topicKeys: <String>[_topicSoftSkills],
      searchKeywords: <String>['leadership', 'ownership', 'team'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['leadership', 'growth', 'ownership'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_qa_communication',
      title: 'QA Communication and Bug Reports',
      subtitle: 'Report issues clearly and align with product teams',
      description: 'A communication-first course for testers and anyone writing sharper bug reports.',
      level: 'Beginner',
      rating: 4.7,
      enrollmentCount: 780,
      estimatedHours: 4,
      color: Color(0xFFFFB74D),
      authorId: 'tomiris_a',
      categoryKey: _topicSoftSkills,
      topicKeys: <String>[_topicSoftSkills],
      searchKeywords: <String>['qa', 'bug report', 'communication'],
      isPopular: false,
      isRecommended: false,
      tags: <String>['qa', 'testing', 'communication'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_data_cleaning_python',
      title: 'Data Cleaning with Python',
      subtitle: 'Messy tables, quick fixes, and notebook habits',
      description: 'Handle missing values, formatting drift, and sanity checks with practical Python routines.',
      level: 'Beginner',
      rating: 4.8,
      enrollmentCount: 1440,
      estimatedHours: 5,
      color: Color(0xFF64B5F6),
      authorId: 'saule_m',
      categoryKey: _topicDataAnalytics,
      topicKeys: <String>[_topicDataAnalytics, _topicProgrammingLanguages],
      searchKeywords: <String>['python', 'data cleaning', 'pandas'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['python', 'analytics', 'data-cleaning'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_sql_window_functions',
      title: 'SQL Window Functions in Practice',
      subtitle: 'Rank, lag, moving windows, and cohort-friendly analysis',
      description: 'Learn the subset of SQL window functions that unlock real analytics work.',
      level: 'Intermediate',
      rating: 4.9,
      enrollmentCount: 1330,
      estimatedHours: 5,
      color: Color(0xFF4FC3F7),
      authorId: 'alina_p',
      categoryKey: _topicSqlDatabases,
      topicKeys: <String>[_topicSqlDatabases, _topicDataAnalytics],
      searchKeywords: <String>['window functions', 'sql', 'postgresql'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['sql', 'postgresql', 'analytics'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_spreadsheet_thinking',
      title: 'Spreadsheet Thinking for Analysts',
      subtitle: 'Shape messy asks into structured analytical workflows',
      description: 'A calmer way to turn business questions into tables, pivots, and clean analysis steps.',
      level: 'Beginner',
      rating: 4.5,
      enrollmentCount: 890,
      estimatedHours: 3,
      color: Color(0xFFA5D6A7),
      authorId: 'saule_m',
      categoryKey: _topicDataAnalytics,
      topicKeys: <String>[_topicDataAnalytics],
      searchKeywords: <String>['spreadsheets', 'analytics', 'tables'],
      isPopular: false,
      isRecommended: false,
      tags: <String>['analytics', 'spreadsheets', 'reporting'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_cohort_analysis',
      title: 'Cohort Analysis Walkthrough',
      subtitle: 'Retention views that tell a product story',
      description: 'Build cohort thinking with practical tables, visual checks, and product language.',
      level: 'Intermediate',
      rating: 4.7,
      enrollmentCount: 770,
      estimatedHours: 5,
      color: Color(0xFF80CBC4),
      authorId: 'maksat_y',
      categoryKey: _topicDataAnalytics,
      topicKeys: <String>[_topicDataAnalytics, _topicSqlDatabases],
      searchKeywords: <String>['cohort', 'retention', 'analytics'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['cohort', 'retention', 'product-analytics'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_ai_product_prompting',
      title: 'AI Prompting for Product Teams',
      subtitle: 'Use AI as a collaborator in research, docs, and iteration',
      description: 'A cross-functional course on using AI well inside product and engineering loops.',
      level: 'Beginner',
      rating: 4.8,
      enrollmentCount: 1710,
      estimatedHours: 4,
      color: Color(0xFFD1A3FF),
      authorId: 'nurislam_g',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi, _topicSoftSkills],
      searchKeywords: <String>['prompting', 'ai product', 'assistant'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['ai', 'product', 'prompting'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_model_monitoring',
      title: 'Model Monitoring Essentials',
      subtitle: 'Track drift, failure cases, and operational trust',
      description: 'Learn what to watch after deploying models and how to communicate health clearly.',
      level: 'Advanced',
      rating: 4.6,
      enrollmentCount: 430,
      estimatedHours: 6,
      color: Color(0xFF9575CD),
      authorId: 'dana_s',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi, _topicDataAnalytics],
      searchKeywords: <String>['monitoring', 'drift', 'mlops'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['ai', 'monitoring', 'mlops'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_nlp_starter',
      title: 'NLP Starter Path',
      subtitle: 'Tokenization, embeddings, and useful text workflows',
      description: 'A light but practical route into NLP concepts for builders and analysts.',
      level: 'Intermediate',
      rating: 4.6,
      enrollmentCount: 620,
      estimatedHours: 6,
      color: Color(0xFFBA68C8),
      authorId: 'nurislam_g',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi],
      searchKeywords: <String>['nlp', 'text', 'embeddings'],
      isPopular: false,
      isRecommended: false,
      tags: <String>['nlp', 'embeddings', 'ai'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_ai_ethics',
      title: 'AI Ethics for Product Decisions',
      subtitle: 'Bias, evaluation boundaries, and release judgment',
      description: 'Use practical cases to think more clearly about responsible AI release decisions.',
      level: 'Intermediate',
      rating: 4.7,
      enrollmentCount: 700,
      estimatedHours: 4,
      color: Color(0xFFE1BEE7),
      authorId: 'nurislam_g',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi, _topicSoftSkills],
      searchKeywords: <String>['ethics', 'responsible ai', 'fairness'],
      isPopular: true,
      isRecommended: false,
      tags: <String>['ethics', 'ai', 'product'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_vector_search_sql',
      title: 'Vector Search and SQL',
      subtitle: 'Blend retrieval ideas with familiar database intuition',
      description: 'A practical bridge between AI retrieval concepts and database-flavored reasoning.',
      level: 'Advanced',
      rating: 4.5,
      enrollmentCount: 390,
      estimatedHours: 5,
      color: Color(0xFF26A69A),
      authorId: 'alina_p',
      categoryKey: _topicSqlDatabases,
      topicKeys: <String>[_topicSqlDatabases, _topicAi],
      searchKeywords: <String>['vector search', 'embeddings', 'sql'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['vector-search', 'sql', 'ai'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_time_series_forecasting',
      title: 'Time Series Forecasting Basics',
      subtitle: 'Seasonality, trends, and practical forecast checks',
      description: 'Learn how to reason about forecasts without pretending every dataset is perfect.',
      level: 'Intermediate',
      rating: 4.6,
      enrollmentCount: 560,
      estimatedHours: 6,
      color: Color(0xFF4DB6AC),
      authorId: 'saule_m',
      categoryKey: _topicDataAnalytics,
      topicKeys: <String>[_topicDataAnalytics, _topicAi],
      searchKeywords: <String>['time series', 'forecasting', 'analytics'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['forecasting', 'analytics', 'ml'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_ai_prototyping_python',
      title: 'AI Prototyping with Python',
      subtitle: 'Ship small assistants and evaluation loops quickly',
      description: 'Prototype AI ideas with simple Python scripts, test sets, and prompt iterations.',
      level: 'Intermediate',
      rating: 4.8,
      enrollmentCount: 940,
      estimatedHours: 6,
      color: Color(0xFF7986CB),
      authorId: 'nurislam_g',
      categoryKey: _topicAi,
      topicKeys: <String>[_topicAi, _topicProgrammingLanguages],
      searchKeywords: <String>['python', 'ai prototype', 'llm'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['python', 'ai', 'prototype'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_database_design_teams',
      title: 'Database Design for Product Teams',
      subtitle: 'Talk about schema tradeoffs in clear product language',
      description: 'Bridge engineering and product conversations around schema decisions and tradeoffs.',
      level: 'Intermediate',
      rating: 4.5,
      enrollmentCount: 610,
      estimatedHours: 5,
      color: Color(0xFF29B6F6),
      authorId: 'alina_p',
      categoryKey: _topicSqlDatabases,
      topicKeys: <String>[_topicSqlDatabases, _topicSoftSkills],
      searchKeywords: <String>['database design', 'schema', 'communication'],
      isPopular: false,
      isRecommended: false,
      tags: <String>['database', 'schema', 'product'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_sql_habits',
      title: 'SQL Habits That Scale',
      subtitle: 'Naming, formatting, and query review discipline',
      description: 'Small habits that make SQL easier to trust, review, and reuse over time.',
      level: 'Beginner',
      rating: 4.7,
      enrollmentCount: 1210,
      estimatedHours: 4,
      color: Color(0xFF81D4FA),
      authorId: 'maksat_y',
      categoryKey: _topicSqlDatabases,
      topicKeys: <String>[_topicSqlDatabases],
      searchKeywords: <String>['sql style', 'queries', 'best practices'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['sql', 'habits', 'queries'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_postgresql_backends',
      title: 'PostgreSQL for Backend Builders',
      subtitle: 'Transactions, constraints, and trustworthy data layers',
      description: 'A backend-oriented PostgreSQL course focused on durable schemas and safe write patterns.',
      level: 'Advanced',
      rating: 4.7,
      enrollmentCount: 570,
      estimatedHours: 7,
      color: Color(0xFF42A5F5),
      authorId: 'rustem_k',
      categoryKey: _topicSqlDatabases,
      topicKeys: <String>[_topicSqlDatabases, _topicProgrammingLanguages],
      searchKeywords: <String>['postgresql', 'backend', 'transactions'],
      isPopular: false,
      isRecommended: true,
      tags: <String>['postgresql', 'backend', 'transactions'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_linux_qa_pipelines',
      title: 'Linux for QA Pipelines',
      subtitle: 'Terminal habits that make testing workflows faster',
      description: 'Use Linux commands and scripts to streamline routine QA and automation tasks.',
      level: 'Intermediate',
      rating: 4.5,
      enrollmentCount: 660,
      estimatedHours: 4,
      color: Color(0xFF66BB6A),
      authorId: 'ilia_v',
      categoryKey: _topicProgrammingLanguages,
      topicKeys: <String>[_topicProgrammingLanguages, _topicSoftSkills],
      searchKeywords: <String>['linux', 'qa', 'automation'],
      isPopular: false,
      isRecommended: false,
      tags: <String>['linux', 'qa', 'automation'],
    ),
    _DiscoveryCourseSeed(
      id: 'course_cybersecurity_everyday',
      title: 'Cybersecurity for Everyday Development',
      subtitle: 'Secure defaults, safer reviews, and practical threat awareness',
      description: 'A team-friendly route into safer development habits for any engineer.',
      level: 'Beginner',
      rating: 4.8,
      enrollmentCount: 1490,
      estimatedHours: 5,
      color: Color(0xFFFF6B6B),
      authorId: 'rustem_k',
      categoryKey: _topicSoftSkills,
      topicKeys: <String>[_topicSoftSkills, _topicProgrammingLanguages],
      searchKeywords: <String>['cybersecurity', 'secure coding', 'threats'],
      isPopular: true,
      isRecommended: true,
      tags: <String>['security', 'cybersecurity', 'secure-coding'],
    ),
  ];

  return seeds
      .map(
        (seed) => buildCommunityCourse(
          id: seed.id,
          title: seed.title,
          subtitle: seed.subtitle,
          description: seed.description,
          level: seed.level,
          rating: seed.rating,
          enrollmentCount: seed.enrollmentCount,
          estimatedHours: seed.estimatedHours,
          color: seed.color,
          author: authors[seed.authorId]!,
          categoryKey: seed.categoryKey,
          topicKeys: seed.topicKeys,
          searchKeywords: seed.searchKeywords,
          isPopular: seed.isPopular,
          isRecommended: seed.isRecommended,
          tags: seed.tags,
          lessons: _defaultCourseLessons(seed.title),
        ),
      )
      .toList(growable: false);
}

List<CommunityCourseLessonPreview> _defaultCourseLessons(String title) {
  return <CommunityCourseLessonPreview>[
    buildCourseLesson(
      '$title: foundations',
      'Build the mental model and vocabulary you need before diving deeper.',
    ),
    buildCourseLesson(
      '$title: worked examples',
      'Study compact examples and the reasoning behind the decisions.',
    ),
    buildCourseLesson(
      '$title: apply the pattern',
      'Turn the idea into a repeatable workflow you can explain to others.',
    ),
  ];
}

class _DiscoveryCourseSeed {
  const _DiscoveryCourseSeed({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.description,
    required this.level,
    required this.rating,
    required this.enrollmentCount,
    required this.estimatedHours,
    required this.color,
    required this.authorId,
    required this.categoryKey,
    required this.topicKeys,
    required this.searchKeywords,
    required this.isPopular,
    required this.isRecommended,
    required this.tags,
  });

  final String id;
  final String title;
  final String subtitle;
  final String description;
  final String level;
  final double rating;
  final int enrollmentCount;
  final int estimatedHours;
  final Color color;
  final String authorId;
  final String categoryKey;
  final List<String> topicKeys;
  final List<String> searchKeywords;
  final bool isPopular;
  final bool isRecommended;
  final List<String> tags;
}
